### PR TITLE
Adding Hillshades/Topography to background of geological map + Improved Error Handling + CPOS and VE for plot_3d

### PR DESCRIPTION
**Pull request by AlexanderJuestel**
# Description

1. A feature to display hillshades below the standard geological was implemented for `plot_map(geo_model,...)`. By default, the standard geological map will be displayed. Setting `show_hillshades = True` will activate the implemented feature. The default `azdeg` is 315 degrees, the default `altdeg` is 45 degrees (ArcGis Standard). They can be changed when plotting the geological map. Currently, the resolution of the hillshades depend on the resolution of the model. This may be changed, depending on the resolution of the topography raster, later on to receive an even better result. The hillshades were calculated with the `LightSource.hillshade(...)` function imported from `matplotlib.colors`. A test notebook was created to demonstrate the new feature (https://github.com/cgre-aachen/gempy/blob/development_alex_juestel/notebooks/experimental/geological_map_hillshades/Hillshade_Example.ipynb). In addition, the tutorial 1.6 was updated and includes a small demonstration of the new feature now. 

2. An improved error handling related to issue #372 was implemented. It will now indicate that you should check the delimiter in your CSV files to make sure that it is set to a `,`.  A sample notebook demonstrating the new error message can be found here: https://github.com/cgre-aachen/gempy/blob/development_alex_juestel/notebooks/experimental/improved_error_handling_csv/Improved_Error_Handling_CSVs.ipynb

3. A third feature implemented includes setting a different camera position (cpos) for the plot_3d function (using PyVista) as well as being able to set the vertical exaggeration of the 3D plot (@banesullivan). 
The default cpos was set manually for now as the PyVista function `get_default_cam_pos` results in a view of the model from below, which is not useful for geological purposes. An example notebook was set up using the Fixture Model von @javoha and can be found here: https://github.com/cgre-aachen/gempy/blob/development_alex_juestel/notebooks/experimental/plot_3d_cpos_ve/Plot_3D_cpos_ve.ipynb. I had to take out the **kwargs in `gpv = Vista(geo_model, **kwargs)`, otherwise it would not have worked. Maybe there is a workaround...

4. A screenshot functionality was implemented for `plot_3d` as well. By providing a `fig_path` as string, a PNG image will be saved. The functionality is demonstrated in the notebook above. The feature is not related to an issue but is a much needed feature to export images rather than taking screenshots. 

Relates to #370, #372, #353 

# Checklist
- [ ] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [ ] My code uses type hinting for function and method arguments and return values.
- [ ] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [ ] I have created tests which entirely cover my code.
- [x] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [ ] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by AlexanderJuestel** [comment]
I updated the description above as I have commited an implementation related to #372

**Comment by AlexanderJuestel** [comment]
I updated the description above as I have pushed an implementation related to #352  to the development branch

**Comment by alexanderzimmerman** [comment]
Looks to me like the tests timed out: https://travis-ci.org/github/cgre-aachen/gempy/builds/675263823

**Comment by pytzcarraldo** [comment]
Yep, they time out at
```
notebooks/tutorials/ch1-Fundamentals/Ch1-10a_2D_Visualization::ipynb::Cell 35 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by AlexanderJuestel** [comment]
So it is one of the tutorials that is causing problems? I checked Tutorial 10 and noticed that I added some lines of codes which do not relate to the pull request. Is it possible to just discard those changes if they cause the error @alexanderzimmerman @pytzcarraldo?

**Comment by alexanderzimmerman** [comment]
> I checked Tutorial 10 and noticed that I added some lines of codes which do not relate to the pull request. Is it possible to just discard those changes if they cause the error @alexanderzimmerman @pytzcarraldo?

@AlexanderJuestel , if you added some unrelated lines of code to a tutorial that you think could be causing the error, then yes please revert such changes and push to this branch again with only the code you want tested and merged.

**Comment by AlexanderJuestel** [comment]
@alexanderzimmerman I removed my lines of codes now.

**Comment by alexanderzimmerman** [comment]
> Is there a way to remove the meta data for tutorial 7 for example? I just ran it once and now it has all this extra meta data

What tutorials do you intend to change with this PR?

**Comment by AlexanderJuestel** [comment]
I intend to change only tutorial 6

**Comment by alexanderzimmerman** [comment]
> I intend to change only tutorial 6

You shouldn't commit any changes to tutorial 7.

It seems to me like maybe you are trying to merge your development branch which has many changes that aren't related to this PR. Can you make a different branch which only changes the intended files and use that for a PR instead?

**Comment by alexanderzimmerman** [comment]
@AlexanderJuestel , make sure to look at [the files changed tab above](https://github.com/cgre-aachen/gempy/pull/377/files) to get an idea of how merging this PR would actually change master.

**Pull request closed without merging**
