### PR TITLE
[WIP] Heavy refactoring: Api rework

### PR DESCRIPTION
**Pull request by Leguark**
# Description
Rework gempy_api.py for better scalability. Mainly to accommodate gempy-server.

Since this pull request is quite heavy - we need to refactor all notebooks for example - I am thinking to combine it with #300 and ~probably with #273 so we can squash the commits together @alexanderzimmerman what do you think~?

### Steps features
- [X] Combine it with #300
- [x] Hide data objects in the KrigingInterpolator 
- [x] Probably also #192 
- [x] start moving faults to be a image of series instead each own class (with deprecation warning for gempy 2.3)

- [X] Delete all deprecations for gempy 2.2

# Checklist
- [ ] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [ ] My code uses type hinting for function and method arguments and return values.
- [ ] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [ ] I have created tests which entirely cover my code.
- [ ] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [ ] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by alexanderzimmerman** [comment]
Seems to me like that's way too much squashing.

Also seems to me like completing #273 should be the first step, which puts me on the critical path 🤔

**Comment by alexanderzimmerman** [comment]
But hey if you manage to do it all at once and it works, don't let me stop you ;)

**Comment by alexanderzimmerman** [comment]
One thing we definitely should avoid is refactoring a bunch of notebooks that we want to delete (or replace with .py) anyway. Or maybe I should give up on the repo size.

**Comment by Leguark** [comment]
Mmm yes, the only way I find to avoid so much squashing is to do #273 first. Okay I will leave this branch with all the refactoring ready and then start taking a look to #273. I really think it should not take soooo long. If I get into a rabbit hole, we can see later how we prioritize the whole thing.

Thanks for the feedback

**Pull request closed without merging**
