### PR TITLE
gempy 2.2.4 preparation

### PR DESCRIPTION
**Pull request by Leguark**
# Description
GemPy release containing changes in loading models and export to rex

### CODE REVIEW

**Comment by Leguark** [comment]
I seriously do not understand why it is detected all those commits @alexanderzimmerman. The file changes at least work

**Comment by alexanderzimmerman** [comment]
> I seriously do not understand why it is detected all those commits @alexanderzimmerman. The file changes at least work

Yeah something is going wrong with merging master to release. The release branch still says its 57 commits behind master after you merged this:
image

**Comment by alexanderzimmerman** [comment]
What kind of merge did you do?

**Comment by Leguark** [comment]
today a normal pull request... well maybe we just need to remove the release and branch it again from master at some point

**Comment by alexanderzimmerman** [comment]
PR is one thing, but when you merge there are a few ways to do it, e.g. a Merge Commit or a Squash and Merge. I thought that a Merge Commit would merge all of the commits in the PR plus one additional commit for the merge. So if that's what you did, then GitHub seems to be screwing something up.

**Comment by alexanderzimmerman** [comment]
I think the default just says "Merge pull request" and does what I was calling Merge Commit: https://docs.github.com/en/github/administering-a-repository/about-merge-methods-on-github

**Comment by alexanderzimmerman** [comment]
@Leguark it sort of looks to me like you did a Squash and Merge.

**Comment by alexanderzimmerman** [comment]
> @Leguark it sort of looks to me like you did a Squash and Merge.

So the reason that all of the commits that you did in a previous PR showed up again is probably that you did a Squash and Merge previously as well.

I think we usually want to do the default style of merge which merges all of the commits plus a merge commit.

**Comment by alexanderzimmerman** [comment]
For the record, I've noticed that rebasing causes a similar problem , so also we generally shouldn't rebase between master and release.

**Pull request merged**
