### PR TITLE
[WIP] Setting up example for Sphinx gallery

### PR DESCRIPTION
**Pull request by WestfalNamur**
Added a simple example for an element in a Sphinx gallery and the
gallery itself.

Requirements: Sphinx-gallery

Setup follows default Sphinx guidelines.
Shows a working example of Sphinx extension.

Working with example .py however it fails when converting gempy/examples.
To reproduce failures do the following:
1. Set up an virtual environment (Python===3.6.8) & source it
2. Pip install gempy requirements.txt
3. Use jupyter nbconvert *.ipynb --to script to convert example notebooks to .py
4. Move the created .py to gempy/example
5. cd into gempy/docs
6. $ make html

### CODE REVIEW

**Comment by pytzcarraldo** [comment]
@WestfalNamur 
What's the next move on this?

**Comment by WestfalNamur** [comment]
This is just a plain implementation of sphinx gallery. For Gempy example implementation the described bug needs to be fixed.

**Comment by alexanderzimmerman** [comment]
I'll want to keep this as a reference for #273 , but this PR isn't being directly worked.

**Comment by alexanderzimmerman** [comment]
Superseded by #380 .

**Pull request closed without merging**
