### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by Leguark**
# Description
Make sure that we compile as few times as possible while running tests

Relates to <issue>

# Checklist
- [x] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [x] My code uses type hinting for function and method arguments and return values.
- X ] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).

- [x] New and existing tests pass locally with my changes.
 
Linked to #340 #319

### CODE REVIEW

**Comment by Leguark** [comment]
@javoha can you add your #340 model to test/conftest

**Comment by pytzcarraldo** [comment]
Is this a WIP pull request? Let me know if you need a review!

**Comment by pytzcarraldo** [comment]
There are quite a bit of changes in the `gempy/core/gempy_api.py` and `gempy/core/model.py` - does that have anything to do with the updated testing? @Leguark

**Comment by alexanderzimmerman** [comment]
What's in the way of merging this PR? It'd be good to have it already when I work #273 . 

I see at least one (potentially large) open question:

> There are quite a bit of changes in the `gempy/core/gempy_api.py` and `gempy/core/model.py` - does that have anything to do with the updated testing? @Leguark

**Comment by Leguark** [comment]
It is all small stuff it was not working as intended that I found while  making the test running. No now features worth mentioning I think

**Pull request merged**
