### PR TITLE
Fix pyvistaqt deprecations

### PR DESCRIPTION
**Pull request by banesullivan**
# Description

Follow up to 063c06371af9c8efb317d69fee8cd744fd9e096d

This sets a minimum version for PyVista since the `pyvistaqt` dependency was added in 063c06371af9c8efb317d69fee8cd744fd9e096d

No reason to have try/excepts for different pyvista versions if you have `pyvistaqt` as a hard dependency

# Checklist

I did not run any of this locally. The diff is small and CI's should catch any serious issues.

### CODE REVIEW

**Comment by banesullivan** [comment]
Also, @Leguark, do you all not have a `conf.py` for sphinx_gallery?

**Comment by Leguark** [comment]
Yes, I agree I just added in case someone had installed gempy this week for the course. But yeah, since at the beginning of the tutorial we will create a new environment probably makes no sense

the config.py is here https://github.com/cgre-aachen/gempy/blob/master/docs/source/conf.py

**Comment by banesullivan** [comment]
> the config.py is here https://github.com/cgre-aachen/gempy/blob/master/docs/source/conf.py

Umm should we remove this so that I can edit the conf.py?:

https://github.com/cgre-aachen/gempy/blob/2b806b5ae319278ac1fae7e483fef67b50935c33/.gitignore#L141

**Comment by Leguark** [comment]
Merged in #490

**Pull request closed without merging**
