### PR TITLE
Add Contribution guidelines

### PR DESCRIPTION
**Pull request by pytzcarraldo**
Addresses issue #270 

Before merging:
- [x] Edit for brevity
- Add and edit templates
   - [x] Pull request
   - [x] Questions
   - [x] Bug reports
   - [x] Feature requests
- [x] Once we have a Question template, directly link to adding an issue using this template in the Questions section.
- [x] Ask Miguel to review

### CODE REVIEW

**Comment by pytzcarraldo** [comment]
@flohorovicic just had the idea to discuss how we  would like people to do proper error handling gempy - I think this is worth discussing within the scope of the contribution guidelines! @alexanderzimmerman

**Comment by alexanderzimmerman** [comment]
FYI, I have made many more changes locally, but I am currently having issues uploading to GitHub, probably because of the internet connection.

**Comment by pytzcarraldo** [comment]
This si ready for merge @alexanderzimmerman or @Leguark

**Comment by alexanderzimmerman** [comment]
> @flohorovicic just had the idea to discuss how we would like people to do proper error handling gempy - I think this is worth discussing within the scope of the contribution guidelines! @alexanderzimmerman

I agree that this is in scope, but I also think we agreed to merge this PR without error handling guidelines and to open a new issue for that.

**Comment by alexanderzimmerman** [comment]
I am not sure how to test that the Question issue template works; but it looks correct and that won't have any side-effects, can be fixed after merging if it doesn't work as expected.

**Comment by alexanderzimmerman** [comment]
I am going to look at the Details of the docs checks next, before approving.

**Comment by alexanderzimmerman** [comment]
@pytzcarraldo , I think that we should have some more explicit expectations about test code in the PR checklist. I wrote down what I think makes sense. I still tried to leave the language quite general, since we don't know right now exactly what kind of tests will be useful for people's contributions. But we also don't want people to think that 100% code coverage means anything, since we shouldn't be merging new code simply because it runs without throwing an error. Should we leave it the way I wrote it or make it a bit more vague still?

**Comment by pytzcarraldo** [comment]
@alexanderzimmerman I think the current wording is fine for now. I specifically like that if offers two lanes of testing: unit testing or use-case/example testing, which I think is quite feasible for gempy

**Comment by alexanderzimmerman** [comment]
Regarding the docs checks, the [Details](https://github.com/cgre-aachen/gempy/pull/294/commits/4a7181f6c05d45cfbe42cdc9531cd7c17b24e70c) show an error which is far outside the scope of this PR. Is @Leguark in charge of the docs? Are these failing the same way for every PR?

Also why is there [a second check with the "push" label](https://github.com/cgre-aachen/gempy/pull/294/checks?check_run_id=479238861)? That fails in the same way.

For the purposes of this PR I will ignore the docs checks. Has someone raised an issue yet?

**Comment by alexanderzimmerman** [comment]
Now I am going through the drudgery of making the Codacy/PR Quality Review pass ;) It is enforcing some Markdown guidelines.

**Comment by alexanderzimmerman** [comment]
I am working through the Codacy quality control from top to bottom and the top two items from the [latest report](https://app.codacy.com/manual/Leguark/gempy/pullRequest?prid=5081980) seem like nonsense to me.

@pytzcarraldo, what Markdown "standards" are being enforced?

**Comment by pytzcarraldo** [comment]
@Leguark set up the codacy stuff - I don't think its especially useful for markdown though

**Comment by alexanderzimmerman** [comment]
> @Leguark set up the codacy stuff - I don't think its especially useful for markdown though

This PR is otherwise ready to merge from my perspective. @Leguark please approve and, if Codacy shouldn't be checking our Markdown files, then is there an option we can set somewhere to avoid this in the future?

**Comment by alexanderzimmerman** [comment]
@Leguark  removed the docs check which needs to be fixed when we update our Sphinx docs process.

So we can just go ahead and merge this!

**Pull request merged**
