### PR TITLE
Add the license to the manifest for inclusion in source code

### PR DESCRIPTION
**Pull request by AndrewAnnex**
distribution

# Description
Please include a summary of the changes.

Relates to <issue>

# Checklist
- [ ] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [ ] My code uses type hinting for function and method arguments and return values.
- [ ] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [ ] I have created tests which entirely cover my code.
- [ ] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [ ] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by Leguark** [comment]
What is this manifest file for? I do not remember when I added :D

**Comment by prisae** [comment]
It excludes stuff from being uploaded to PyPi.

**Comment by prisae** [comment]
Sorry. MANIFEST *includes* stuff uploaded to PyPi. You should, for instance, have LICENSE in the MANIFEST file.

This is a bit a weird thing with `setuptools_scm`, because with that tool it flips, everything is uploaded to PyPi, and you use MANIFEST to *exclude* files from being uploaded.

**Comment by AndrewAnnex** [comment]
You can both include and exclude files using the manifest, it’s always best practice for the license file to be included in the source distribution (but also specifically related to the conda forge recipe for gempy)

-Andrew Annex

**Comment by prisae** [comment]
You are right. What changes is the default. With setup by default nothing is includeded, and you can use MANIFEST to include things specifically. When using `setuptools_scm` by default everything is included, and you have to use MANIFEST to explicitly exclude things. But MANIFEST as such can be used for either. Does that make sense?

**Comment by AndrewAnnex** [comment]
It does, but using it seems to be a break in convention as other tools don’t necessarily know that the manifest has been inverted. Better to be explicit than implicit 

-Andrew Annex

**Comment by Leguark** [comment]
alright thanks for the clarification!

**Pull request merged**
