### PR TITLE
# Added new model for simple geometry examples

### PR DESCRIPTION
**Pull request by javoha**
# Description
(Re)Added a new model with a combination of folding, faulting and unconformity to the simple geometry example model suite.

# Checklist
- [x] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [x] My code uses type hinting for function and method arguments and return values.
- [x] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [x] I have created tests which entirely cover my code.
- [x] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [x] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by javoha** [comment]
> Looks good, thanks for adding! Only thing is that we maybe need better naming schemes for the input data rather than "jan_models" etc 😄

Agreed, doesn't even contain my last name ;) ... In my defense - I did not start naming them that way.

**Comment by alex-schaaf** [comment]
So gh pages travis fails again @Leguark @alexanderzimmerman 

```
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
The command "pipenv run make html" exited with 2.
```

**Comment by alexanderzimmerman** [comment]
> So gh pages travis fails again @Leguark @alexanderzimmerman
> 
> ```
> Makefile:20: recipe for target 'html' failed
> make: *** [html] Error 2
> The command "pipenv run make html" exited with 2.
> ```

I explored this a bit on #452 . Now I am also seeing a warning about pip's handling of requirements.txt changing:

```
$ pipenv run make html
requirements.txt found, instead of Pipfile! Converting…
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
```

I haven't touched our pip deployment at all yet, so I don't think I should dig into this further without @Leguark . I'd like to learn about it though. Maybe @Leguark and I can dig into it together tomorrow.

**Comment by alexanderzimmerman** [comment]
In the meantime, @javoha , I put some thought into whether any more should be done regarding the testing items in the PR checklist. Since you only added an example which is run by our gh-pages deployment, I would consider the new code to be tested (just as well as any of our other examples are tested). So I checked two more boxes; but the last box is still unchecked because I didn't run the code locally and because gh-pages is failing.

**Comment by alex-schaaf** [comment]
`Pipfile`? Are they now using `pipenv`?

**Comment by javoha** [comment]
Mmh I am really not sure - I ran the model again locally and everything works fine. @Leguark and me even tested the document building locally and everything worked.  Any suggestions?

**Comment by alexanderzimmerman** [comment]
I'll test this PR's branch and see if I get the same thing.

**Comment by javoha** [comment]
> I'll test this PR's branch and see if I get the same thing.

Just be aware that you need to change the path to the data if you run it locally because I changed the input data and it will pull it from master otherwise.

**Comment by alexanderzimmerman** [comment]
> > I'll test this PR's branch and see if I get the same thing.
> 
> Just be aware that you need to change the path to the data if you run it locally because I changed the input data and it will pull it from master otherwise.

If you have to give me extra instructions then that's also maybe a reason that Travis would fail. I don't actually understand what you're telling me to do.

When I checkout this PR's branch

```
$ git fetch origin pull/459/head:pr459
From https://github.com/cgre-aachen/gempy
 * [new ref]           refs/pull/459/head -> pr459

$ git checkout pr459
Switched to branch 'pr459'
```
and then run your example, I get the same error that the Travis check showed:
```
(gempy) PS C:\Users\zimme\Desktop\Jan-PR\gempy> python .\examples\examples\geometries/7_combination.py
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\zimme\anaconda3\envs\gempy\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Active grids: ['regular']
Traceback (most recent call last):
  File ".\examples\examples\geometries/7_combination.py", line 43, in <module>
    geo_data.set_is_fault(['Fault_Series'])
  File "C:\Users\zimme\anaconda3\envs\gempy\lib\site-packages\gempy\core\model.py", line 687, in set_is_fault
    self._faults.set_is_fault(feature_fault, toggle=toggle)
  File "C:\Users\zimme\anaconda3\envs\gempy\lib\site-packages\gempy\core\data_modules\stack.py", line 67, in set_is_fault
    assert np.isin(series_fault, self.df.index).all(), 'series_faults must already ' \
AssertionError: series_faults must already exist in the the series df.
```

**Comment by alexanderzimmerman** [comment]
See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Comment by javoha** [comment]
Ok maybe you can give me adivce on how to do that: The pull request contains the new model (combination.py) and changes to the corresponding input data (examples/data/input_data/jan_models/...). For all the example models the data is not pulled from the relative path though but from:

**Comment by javoha** [comment]
Ok maybe you can give me adivce on how to do that: The pull request contains the new model (combination.py) and changes to the corresponding input data (examples/data/input_data/jan_models/...). For all the example models the data is not pulled from the relative path though but from:

**Comment by javoha** [comment]
Ok maybe you can give me adivce on how to do that: The pull request contains the new model (combination.py) and changes to the corresponding input data (examples/data/input_data/jan_models/...). For all the example models the data is not pulled from the relative path though but from:

**Comment by javoha** [comment]
So I created a new model (combination.py) and changes the input data. To run it locally I need to create a relative path to the new input data, as I can not pull it the same way as it is done for the models in general from github - as it is noth there yet. 

```
data_path = 'https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/'
geo_data = gp.create_data('horizontal', extent=[0, 1000, 0, 1000, 0, 1000], resolution=[50, 50, 50],
                          path_o=data_path + "/data/input_data/jan_models/model1_orientations.csv",
                          path_i=data_path + "/data/input_data/jan_models/model1_surface_points.csv")
```

For the commit and the pull request I changed that path so it is coherent with all the other examples.

**Comment by alexanderzimmerman** [comment]
> So I created a new model (combination.py) and made changes to the input data. To run it locally I need to create a relative path to the new input data, as I can not pull it the same way as it is done for the models in general from github - as it is noth there yet.
> 
> ```
> data_path = 'https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/'
> geo_data = gp.create_data('horizontal', extent=[0, 1000, 0, 1000, 0, 1000], resolution=[50, 50, 50],
>                           path_o=data_path + "/data/input_data/jan_models/model1_orientations.csv",
>                           path_i=data_path + "/data/input_data/jan_models/model1_surface_points.csv")
> ```
> 
> For the commit and the pull request I changed that path so it is coherent with all the other examples.

If I understand you correctly, then the Travis check should definitely fail because it tries to pull non-existent data. 

Why is your data not there yet?

**Comment by javoha** [comment]
Because it is part of this pull request and thus cannot be on 

`https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/`

as far as I understand?

**Comment by alexanderzimmerman** [comment]
> Because it is part of this pull request and thus cannot be on
> 
> `https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/`
> 
> as far as I understand?

Explain to me how this PR should affect https://raw.githubusercontent.com/cgre-aachen/gempy_data . I am missing something.

**Comment by javoha** [comment]
Maybe my way of thinking is wrong: So I changed those files:

`examples\data\input_data\jan_models\model7_orientations.csv`
`examples\data\input_data\jan_models\model7_surface_points.csv`

And I was hoping with the pull request they would be added to `https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/`. So that I can access them for my model as it is done for all other models. Is that wrong? Do I need to do a seperate pull request for the data?

**Comment by alexanderzimmerman** [comment]
Sounds to me like you want to put the data here: https://github.com/cgre-aachen/gempy_data

**Comment by alexanderzimmerman** [comment]
> And I was hoping with the pull request they would be added to `https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/`. So that I can access them for my model as it is done for all other models. Is that wrong? Do I need to do a seperate pull request for the data?

I do not know any mechanism that would be automating this. But I also don't remember being directed how to handle this kind of data. Did @Leguark make this gempy_data repo when he merged the big Sphinx PR?

**Comment by javoha** [comment]
Ok I understand the poblem now, thought there was some kind of automation for this. BUt I hope you also see my point: If I understand correctly now, whenever we want a new model in gempy we need this workflow:

**Comment by alexanderzimmerman** [comment]
@Leguark should probably sync the access rights between gempy and gempy_data .

**Comment by alexanderzimmerman** [comment]
> Ok I understand the poblem now, thought there was some kind of automation for this. BUt I hope you also see my point: If I understand correctly now, whenever we want a new model in gempy we need this workflow:
> 
> 1. Merge data with `gempy_data/master`
> 2. Wait for approval
> 3. Merge rest with GemPy

Yeah, though we should have it so anyone who can approve PR's and merge to gempy master can also add the data to gempy_data. Hopefully @Leguark can fix that part of it soon. 

I think it's still right for you to open the PR before the data is there when you don't have access rights for adding the data. We can always re-trigger the Travis build after adding the data. If you could write to gempy_data, then it'd be least confusing to add the data before making the PR. The downside would be if something is wrong with the data and the data repo gets messier.

**Comment by alexanderzimmerman** [comment]
> Edit: Does that also mean that the data in the Gempy master is unnecessary?

I don't really know what the plan is, but yeah, the point would be to not put the data into the gempy repository.

**Comment by javoha** [comment]
Small update: I pushed the update data to https://github.com/cgre-aachen/gempy_data so hopefully this error should now be gone. NO idea how that works but is there a way to "restart" Travis - without pushing something else as this was an "external" issue?

**Comment by alexanderzimmerman** [comment]
> Small update: I pushed the update data to https://github.com/cgre-aachen/gempy_data so hopefully this error should now be gone. NO idea how that works but is there a way to "restart" Travis - without pushing something else as this was an "external" issue?

Great, I restarted the build ;)

**Comment by alexanderzimmerman** [comment]
Oh  yeah, because of #470 I also have to trigger the push check again.

**Comment by alexanderzimmerman** [comment]
The gh-pages deployment check on Travis failed because of #466 . So I'll rebase this branch on master now.

**Pull request merged**
