### PR TITLE
Add set_orientation_from_neighbours

### PR DESCRIPTION
**Pull request by domist07**
# Description
The two modyfied files are:
https://github.com/domist07/gempy/blob/master/gempy/api_modules/setters.py (functions itself, starts at line 189) and
https://github.com/domist07/gempy/blob/master/test/test_api/test_geometry_api.py (test)

Relates to #318 

# Checklist
- [✔] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [✔] My code uses type hinting for function and method arguments and return values.
- [✔] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [✔] I have created tests which entirely cover my code.
- [✔] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [✔] New and existing tests pass locally with my changes.

### CODE REVIEW

**Review by Leguark — APPROVED** [review]
Thank you for the contribution Dominik!

Sorry for the delay but I have been fighting with Travis for a while with the automatic testing. Testing looks great now! Thanks for the effort refactoring the pull request

**Comment by domist07** [comment]
With pleasure! Nice that the function is now implemented😊.

**Comment by Magniel** [comment]
Hi guys! Could you please tell me how to manage this brand new function? I'd like to use it in my gempy code as I don't have accurate informations regarding the orientations.

**Comment by domist07** [comment]
Simply copy this file (https://github.com/domist07/gempy/blob/master/gempy/api_modules/setters.py) and replace the existing in your gempy python folder (path_to_packages/gempy/api_modules/).

You can test the functionality by running this code snippet:
```
data_path = 'https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/'
path_to_data = data_path + "/data/input_data/jan_models/"

geo_data = gp.create_data('fault', extent=[0, 1000, 0, 1000, 0, 1000],
                              resolution=[50, 50, 50],
                          path_o=path_to_data + "model5_orientations.csv",
                          path_i=path_to_data + "model5_surface_points.csv")

# count orientations before orientation calculation
length_pre = geo_data._orientations.df.shape[0]

# find neighbours
neighbours = gp.select_nearest_surfaces_points(geo_data, geo_data._surface_points.df, 2)
# calculate all fault orientations
gp.set_orientation_from_neighbours_all(geo_data, neighbours)

# count orientations after orientation calculation
length_after = geo_data._orientations.df.shape[0]

If np.array_equal(geo_data._surface_points.df.shape[0], length_after-length_pre)
    print("set_orientation_from_neighbours works 😊")
```

**Comment by Magniel** [comment]
Hi Domist.
Thanks for your reply.
I've followed the mentionned step -> replacing the setters.py original script by yours.
Questions ;
-> Do I still have to call a .csv file for orientations? and defined path_i ?
-> Do I have to manage a function called "set_orientation_from_neighbours" in my script?
-> Practically, what must I do now to run your script ?
Sorry for the noob's questions but I'm a bit lost in the process (I'm definitely not an high skilled python developper :-/)
Thanks by advance for your greatfull help ;-)
Mat

**Comment by domist07** [comment]
1. Do I still have to call a .csv file for orientations? and defined path_i ?
No, my functions appends the orientations to the gempy model. You can show them by `geo_model._orientations.df`
2. Do I have to manage a function called "set_orientation_from_neighbours" in my script?
No, if you have replaced the file in your gempy folder it will be automatically imported with GemPy.
3. Practically, what must I do now to run your script ?
Please follwing one of the existing [GemPy-Tutorials](https://docs.gempy.org/tutorials/index.html#chapter-1-gempy-fundamentals) with the changes, that you delete `path_o=XXX` in `gp.init_data(...)` and add this two lines after this command.
```
neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
gp.set_orientation_from_neighbours_all(geo_model, neighbours)
```

**Comment by Magniel** [comment]
First of all, thank you @domist07 for your time and help! 
I've followed your steps, but it doesn't work

my script (built on the basis of tutorial 1.1, - but using surface_points_df rather than directly path_i)

%matplotlib inline
from pyvista import set_plot_theme
set_plot_theme('document')

import gempy as gp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

# Setting options
np.random.seed(1515)
pd.set_option('precision', 2)

geo_model = gp.create_model('GEMPY_tuto1.1_brussels')
data_path_i = r'C:\Users\magniel\Desktop\GEMPY\GEMPY_TUTO_points.csv'
df_i = pd.read_csv (data_path_i,sep=';')

gp.init_data(geo_model, [146500,148000,170000,171500,-100,50],[20,20,20],
             surface_points_df = df_i,
             default_values=True)
neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
gp.set_orientation_from_neighbours_all(geo_model, neighbours)

=> here is what I get :

Active grids: ['regular']
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-c73e7098dad9> in <module>
      3              surface_points_df = df_i,
      4              default_values=True)
----> 5 neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
      6 gp.set_orientation_from_neighbours_all(geo_model, neighbours)

AttributeError: module 'gempy' has no attribute 'select_nearest_surfaces_points'


It seems to be a problem with select_nearest_surfaces_points, not recognized...
Although I've deleted to original setters file on C:\Users\...\AppData\Roaming\Python\Python38\site-packages\gempy\api_modules. I 've also restarted my computer...

What's wrong here according to you?
Could you please correct my script then I could better figure out my mistake?

**Comment by domist07** [comment]
Did you get this warning?
`UserWarning: Regular grid won't be initialize, you will have to create a gridafterwards. See gempy.set_grid`
Works this?
`geo_model.set_orientation_from_neighbours_all(neighbours)`

**Comment by Magniel** [comment]
I did'nt get this warning.
I tried with 
`geo_model.set_orientation_from_neighbours_all(neighbours)`
=>
```
  gp.init_data(geo_model,` [146500,148000,170000,171500,-100,50],[20,20,20],
               surface_points_df = df_i,
               default_values=True)
  neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
  geo_model.set_orientation_from_neighbours_all(neighbours)
```

But I receive the same message, which seems obvious as the problem  comes from select_nearest_surfaces_points, no?

```

Active grids: ['regular']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-681f266064f1> in <module>
      3              surface_points_df = df_i,
      4              default_values=True)
----> 5 neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
      6 geo_model.set_orientation_from_neighbours_all(neighbours)

AttributeError: module 'gempy' has no attribute 'select_nearest_surfaces_points'
```

**Comment by domist07** [comment]
This should work:
```
neighbours = gp.api_modules.setters.select_nearest_surfaces_points(geo_model, geo_model._surface_points.df, 2)
gp.api_modules.setters.set_orientation_from_neighbours_all(geo_model, neighbours)
```
@Leguark what has to be adjusted so that the function is found without the addition 'api_modules.setters.'?

**Comment by Magniel** [comment]
I tried with your new code :
    `gp.init_data(geo_model, [146500,148000,170000,171500,-100,50],[20,20,20],
                 surface_points_df = df_i,
                 default_values=True)
    neighbours = gp.api_modules.setters.select_nearest_surfaces_points(geo_model, geo_model._surface_points.df, 2)
    gp.api_modules.setters.set_orientation_from_neighbours_all(geo_model, neighbours)`

Now I get this error message :

      `
      Active grids: ['regular']
      ---------------------------------------------------------------------------
      ValueError                                Traceback (most recent call last)
      <ipython-input-11-6d63895637c2> in <module>
            2 gp.init_data(geo_model, [146500,148000,170000,171500,-100,50],[20,20,20],
            3              surface_points_df = df_i,
      ----> 4              default_values=True)
            5 #neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
            6 #geo_model.set_orientation_from_neighbours_all(neighbours)
      
      ~\.conda\envs\gempy\lib\site-packages\gempy\gempy_api.py in init_data(geo_model, extent, resolution, **kwargs)
          186 
          187     if 'surface_points_df' in kwargs:
      --> 188         geo_model.set_surface_points(kwargs['surface_points_df'], **kwargs)
          189         # if we set the surfaces names with surfaces they cannot be set again on orientations or pandas will complain.
          190         kwargs['update_surfaces'] = False
      
      ~\.conda\envs\gempy\lib\site-packages\gempy\core\model.py in set_surface_points(self, table, **kwargs)
          940 
          941         if update_surfaces is True:
      --> 942             self.add_surfaces(table[surface_name].unique())
          943 
          944         c = np.array(self._surface_points._columns_i_1)
      
      ~\.conda\envs\gempy\lib\site-packages\gempy\core\model.py in add_surfaces(self, surface_list, update_df)
          737     def add_surfaces(self, surface_list: Union[str, list], update_df=True):
          738         self._surfaces.add_surface(surface_list, update_df)
      --> 739         self._surface_points.df['surface'].cat.add_categories(surface_list, inplace=True)
          740         self._orientations.df['surface'].cat.add_categories(surface_list, inplace=True)
          741         self.update_structure()
      
      ~\.conda\envs\gempy\lib\site-packages\pandas\core\accessor.py in f(self, *args, **kwargs)
           97         def _create_delegator_method(name):
           98             def f(self, *args, **kwargs):
      ---> 99                 return self._delegate_method(name, *args, **kwargs)
          100 
          101             f.__name__ = name
      
      ~\.conda\envs\gempy\lib\site-packages\pandas\core\arrays\categorical.py in _delegate_method(self, name, *args, **kwargs)
         2562 
         2563         method = getattr(self._parent, name)
      -> 2564         res = method(*args, **kwargs)
         2565         if res is not None:
         2566             return Series(res, index=self._index, name=self._name)
      
      ~\.conda\envs\gempy\lib\site-packages\pandas\core\arrays\categorical.py in add_categories(self, new_categories, inplace)
         1026         if len(already_included) != 0:
         1027             raise ValueError(
      -> 1028                 f"new categories must not include old categories: {already_included}"
         1029             )
         1030         new_categories = list(self.dtype.categories) + list(new_categories)
      
      ValueError: new categories must not include old categories: {'quat', 'komo', 'gl', 'li', 'kosm'}
      `

Any idea of what is wrong?

**Comment by domist07** [comment]
No, but the error isn't in my new code snippet. The error message says, that it's in the command
`gp.init_data(geo_model, [146500,148000,170000,171500,-100,50],[20,20,20], surface_points_df = df_i, default_values=True)`
Which GemPy version did you use?
At the moment I use 2.2.6 and add my snippet manually.

**Comment by Magniel** [comment]
I use the version 2.2.7 of gempy, on python 3.7.9

**Comment by domist07** [comment]
With this version of GemPy I had problems, too. Please try with a lower version.

**Comment by Magniel** [comment]
I've retried with the version 2.2.6, but I've got the same issue.
Actually, I've a first error (error 1) pointing on neighbours :
    
    Active grids: ['regular']
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-7-cb27835b22ff> in <module>
          4              surface_points_df = df_i,
          5              default_values=True)
    ----> 6 neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
          7 geo_model.set_orientation_from_neighbours_all(neighbours)
          8 
    AttributeError: module 'gempy' has no attribute 'select_nearest_surfaces_points
    

and Then, if run once again the last cell

    gp.init_data(geo_model, [146500,148000,170000,171500,-100,50],[20,20,20],
                 #orientations_df = df_o,
                 surface_points_df = df_i,
                 default_values=True)
    neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
    geo_model.set_orientation_from_neighbours_all(neighbours)

I get a new error instead (error 2) :

    Active grids: ['regular']
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-8-cb27835b22ff> in <module>
          3              #orientations_df = df_o,
          4              surface_points_df = df_i,
    ----> 5              default_values=True)
          6 neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
          7 geo_model.set_orientation_from_neighbours_all(neighbours)
    
    ~\AppData\Local\Continuum\anaconda2\envs\gempy 226\lib\site-packages\gempy\gempy_api.py in init_data(geo_model, extent, resolution, **kwargs)
        186 
        187     if 'surface_points_df' in kwargs:
    --> 188         geo_model.set_surface_points(kwargs['surface_points_df'], **kwargs)
        189         # if we set the surfaces names with surfaces they cannot be set again on orientations or pandas will complain.
        190         kwargs['update_surfaces'] = False
    
    ~\AppData\Local\Continuum\anaconda2\envs\gempy 226\lib\site-packages\gempy\core\model.py in set_surface_points(self, table, **kwargs)
        940 
        941         if update_surfaces is True:
    --> 942             self.add_surfaces(table[surface_name].unique())
        943 
        944         c = np.array(self._surface_points._columns_i_1)
    
    ~\AppData\Local\Continuum\anaconda2\envs\gempy 226\lib\site-packages\gempy\core\model.py in add_surfaces(self, surface_list, update_df)
        737     def add_surfaces(self, surface_list: Union[str, list], update_df=True):
        738         self._surfaces.add_surface(surface_list, update_df)
    --> 739         self._surface_points.df['surface'].cat.add_categories(surface_list, inplace=True)
        740         self._orientations.df['surface'].cat.add_categories(surface_list, inplace=True)
        741         self.update_structure()
    
    ~\AppData\Local\Continuum\anaconda2\envs\gempy 226\lib\site-packages\pandas\core\accessor.py in f(self, *args, **kwargs)
         97         def _create_delegator_method(name):
         98             def f(self, *args, **kwargs):
    ---> 99                 return self._delegate_method(name, *args, **kwargs)
        100 
        101             f.__name__ = name
    
    ~\AppData\Local\Continuum\anaconda2\envs\gempy 226\lib\site-packages\pandas\core\arrays\categorical.py in _delegate_method(self, name, *args, **kwargs)
       2562 
       2563         method = getattr(self._parent, name)
    -> 2564         res = method(*args, **kwargs)
       2565         if res is not None:
       2566             return Series(res, index=self._index, name=self._name)
    
    ~\AppData\Local\Continuum\anaconda2\envs\gempy 226\lib\site-packages\pandas\core\arrays\categorical.py in add_categories(self, new_categories, inplace)
       1026         if len(already_included) != 0:
       1027             raise ValueError(
    -> 1028                 f"new categories must not include old categories: {already_included}"
       1029             )
       1030         new_categories = list(self.dtype.categories) + list(new_categories)
    
    ValueError: new categories must not include old categories: {'kosm', 'gl', 'quat', 'li', 'komo'}
 
I seems that the problem comes from gp.select_nearest_surfaces_points() linked to error 1, don't you think?

Please note that I tried your 3 solutions, leading to the same error message :

option 1
    `neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
     gp.set_orientation_from_neighbours_all(geo_model, neighbours)`
option 2       
    `neighbours = gp.select_nearest_surfaces_points(geo_model, geo_data._surface_points.df, 2)
    geo_model.set_orientation_from_neighbours_all(neighbours)`
option 3
    `neighbours = gp.api_modules.setters.select_nearest_surfaces_points(geo_model, geo_model._surface_points.df, 2)
    gp.api_modules.setters.set_orientation_from_neighbours_all(geo_model, neighbours)`

**Comment by domist07** [comment]
If I try to reproduce it, _error 1_ doesn't arrise, if I use _option 3_. After downgrading gempy, did you insert the edited setters file again manually?
Did you use the data from the first tutorial? Otherwise could you send me your data? 
I see that you use Anaconda 2. I use Anaconda 3.
According error 2 I couldn't help you from afar. Please open a new issue, that the other contributers help you.

**Comment by Magniel** [comment]
So far..
-> I've downgraded gempy in v 2.2.6
-> I've deleted anaconda 2 to be sure that I use anaconda 3
-> I've checked if the setters file is well replaced by yours
(the link on my pc is the following : C:\Users\magniel\AppData\Roaming\Python\Python38\site-packages\gempy\api_modules). 

To simplify the issue, I switched on the tutorial script rather than my own script & data. 
Here is the script now:

    # Importing GemPy
    import gempy as gp
    
    # Importing auxiliary libraries
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import os
    
    # Setting options
    np.random.seed(1515)
    pd.set_option('precision', 2)
    
    geo_model = gp.create_model('Tutorial_ch1_1_Basics')
    
    data_path = 'https://raw.githubusercontent.com/cgre-aachen/gempy_data/master/'
    # Importing the data from CSV-files and setting extent and resolution
    gp.init_data(geo_model, [0, 2000., 0, 2000., 0, 750.], [50, 50, 50],
                 path_i=data_path + "/data/input_data/getting_started/"
                                    "simple_fault_model_points.csv",
                 default_values=True)
    neighbours = gp.api_modules.setters.select_nearest_surfaces_points(geo_model, geo_model._surface_points.df, 2)
    gp.api_modules.setters.set_orientation_from_neighbours_all(geo_model, neighbours)

Error 1 remains active while Error 2 is no longer active (I'll try to solve this later). 
It seems that the new functions in your setter file isn't recognized ?

**Comment by domist07** [comment]
Sorry Magniel but I can't tell you what the problem is. Everything is the same for me and it works.
To use the functions anyway, you can copy the 3 functions directly into your script and then call them directly.
For example:
```python
def select_nearest_surfaces_points(geo_model, surface_points, searchcrit):
   [...]

select_nearest_surfaces_points(geo_model, geo_model._surface_points.df, 2)
```

**Comment by Magniel** [comment]
The 3 functions work perfectly while implemented directly on my script. I'll work this way, it's not a big deal.
Thanks again for your help @domist07. I appreciate it. I wish you a better year than the previous one! It won't be that difficult I guess :-)

**Comment by domist07** [comment]
Your welcome! 😊
Thanks, I wish you a happy new year too.

**Pull request merged**
