### PR TITLE
Moved Petrel integration to subsurface module

### LINKED ISSUE #90: Read-in of exported Petrel fault stick files
Read function for kingdom fault sticks / charisma fault sticks files (essentially chaotically delimited csv) as fault evidence (grouped by stick per fault)

### PR DESCRIPTION
**Pull request by pytzcarraldo**
# Description
Removed the Petrel integration (io) functionality for import/export of fault sticks and horizon grids and moved it to the swung `subsurface` module.

Resolves #90 

# Checklist
The PR only removes utility code previously used by me that is out of scope for GemPy.

### CODE REVIEW

**Comment by pytzcarraldo** [comment]
Paging @Leguark to review / accept this so it can be closed 😏

**Comment by Leguark** [comment]
you should have move it to in review! Otherwise I dont find it :D

**Comment by pytzcarraldo** [comment]
Right! Thanks for reminding me 😄

**Comment by Leguark** [comment]
Did you add it to subsurface?

**Comment by pytzcarraldo** [comment]
Yep, merged it into the master branch there. I detailed that in #90 and not here for some odd reason

**Comment by Leguark** [comment]
Can you create a a test in gempy/test/test_integrations/test_subsurface

Using 

`subsurface= pytest.importorskip("subsurface")`

**Comment by Leguark** [comment]
are you planning to do this or do we merge it and whenever we start making subsurface content we add the test?

**Comment by pytzcarraldo** [comment]
I'd say we merge it and make the tests for subsurface content, so we don't inflate the testing in gempy?

**Comment by Leguark** [comment]
probably we will need to have test in both sides but yeah lets do it when we give more love to subsurface

**Pull request merged**
