### PR TITLE
Adding Hillshades/Topography to background of geological map + Improved Error Handling + CPOS and VE for plot_3d

### PR DESCRIPTION
**Pull request by AlexanderJuestel**
1. A feature to display hillshades below the standard geological was implemented for plot_map(geo_model,...). By default, the standard geological map will be displayed. Setting show_hillshades = True will activate the implemented feature. The default azdeg is 315 degrees, the default altdeg is 45 degrees (ArcGis Standard). They can be changed when plotting the geological map. Currently, the resolution of the hillshades depend on the resolution of the model. This may be changed, depending on the resolution of the topography raster, later on to receive an even better result. The hillshades were calculated with the LightSource.hillshade(...) function imported from matplotlib.colors. A test notebook was created to demonstrate the new feature (https://github.com/cgre-aachen/gempy/blob/development_alex_juestel/notebooks/experimental/geological_map_hillshades/Hillshade_Example.ipynb). In addition, the tutorial 1.6 was updated and includes a small demonstration of the new feature now.

2. An improved error handling related to issue #372 was implemented. It will now indicate that you should check the delimiter in your CSV files to make sure that it is set to a ,. A sample notebook demonstrating the new error message can be found here: https://github.com/cgre-aachen/gempy/blob/development_alex_juestel/notebooks/experimental/improved_error_handling_csv/Improved_Error_Handling_CSVs.ipynb

3. A third feature implemented includes setting a different camera position (cpos) for the plot_3d function (using PyVista) as well as being able to set the vertical exaggeration of the 3D plot (@banesullivan).
The default cpos was set manually for now as the PyVista function get_default_cam_pos results in a view of the model from below, which is not useful for geological purposes. An example notebook was set up using the Fixture Model von @javoha and can be found here: https://github.com/cgre-aachen/gempy/blob/development_alex_juestel/notebooks/experimental/plot_3d_cpos_ve/Plot_3D_cpos_ve.ipynb. I had to take out the **kwargs in gpv = Vista(geo_model, **kwargs), otherwise it would not have worked. Maybe there is a workaround...

4. A screenshot functionality was implemented for plot_3d as well. By providing a fig_path as string, a PNG image will be saved. The functionality is demonstrated in the notebook above. The feature is not related to an issue but is a much needed feature to export images rather than taking screenshots.

Relates to #370, #372, #353

# Checklist
- [x] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [x] My code uses type hinting for function and method arguments and return values.
- [x] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [ ] I have created tests which entirely cover my code.
- [x] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [x] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by AlexanderJuestel** [comment]
@alexanderzimmerman, the previous pull request should be deleted. I created a new development branch and pushed only the changed files to the new branch and opened a pull request only containing the changed files :)

**Comment by alexanderzimmerman** [comment]
@AlexanderJuestel , thanks for cleaning this up! You mentioned to me on Slack that you wanted to talk about the review workflow. Right now there's not much for us to do as reviewers. We need you to attempt going through the PR checklist and to let us know where you get stuck. Most importantly, some of the tests aren't passing. Did you run the tests locally on this branch?

**Comment by AlexanderJuestel** [comment]
@alexanderzimmerman, do you mean the travis-ci/pr and push checks? I will check them out.

**Comment by alexanderzimmerman** [comment]
> do you mean the travis-ci/pr and push checks? 

I was referring the the checklist in the description of the PR. The last checkbox asks you to run the tests locally, rather than only relying on Travis to run the tests. But also yes, it also helps for you to look at the reports from Travis-CI. Thanks!

**Comment by AlexanderJuestel** [comment]
@alexanderzimmerman, I ran the implemented features in my model notebooks and still use them freuqently. Could you maybe give me some more information regarding other tests that I still have to run?

**Comment by AlexanderJuestel** [comment]
Okay, got it

image

**Comment by alexanderzimmerman** [comment]
> @alexanderzimmerman, I ran the implemented features in my model notebooks and still use them freuqently. Could you maybe give me some more information regarding other tests that I still have to run?

I'm not aware of any more tests that you need to run.


@Leguark, what's going wrong with the continuous-integration/travis-ci/pr check?


@AlexanderJuestel , in the meantime you can still run through the first four checklist items (which right now appear unchecked to me).

**Comment by AlexanderJuestel** [comment]
I added type hints to the code and checked for any other issues in PyCharm.

**Comment by alexanderzimmerman** [comment]
Will @Leguark or @pytzcarraldo  review this for test coverage?

**Comment by Leguark** [comment]
Hi @AlexanderJuestel thanks for the pull request! It looks very good. I am going to merge it to my branch instead master for now and I will push a test so you can see where it goes exactly!

**Comment by AlexanderJuestel** [comment]
Hey @Leguark thank you very much :)

**Pull request merged**
