### PR TITLE
[WIP] fixes for sparse theano functions needing fault matrix

### PR DESCRIPTION
**Pull request by AndrewAnnex**

### CODE REVIEW

**Comment by Leguark** [comment]
Thanks to check this! 

Can you make a small test for the sparse functionality so I won't break it again next time I touch something?

Also taking advantage that you are looking at this, a colleague @denise91  of mine pointed me out that one of the sparse solver of scipy is much better than the other. GemPy is using 
`from scipy.sparse.linalg import spsolve`
@denise91 can you confirm that gempy is using the bad one and if yes @AndrewAnnex do you mind to change it?

Cheers

**Comment by AndrewAnnex** [comment]
it looks like something significant is wrong with the expected theano shapes, until that code is better documented I don't think I will be able to make progress on it. @Leguark feel free to take this pr on, I have enabled edits from maintainers on this pr

**Comment by alexanderzimmerman** [comment]
> Also taking advantage that you are looking at this, a colleague @denise91 of mine pointed me out that one of the sparse solver of scipy is much better than the other. GemPy is using
> `from scipy.sparse.linalg import spsolve`

I think it's best to change one thing at a time. Regarding using a more efficient sparse linear system solver, I am just waiting on a working test case at #276 .

**Comment by AndrewAnnex** [comment]
@alexanderzimmerman I agree with that, changes to the solver should be in a different pr

**Comment by pytzcarraldo** [comment]
What state is this PR in? I've tagged it as WIP for now. Let me (or maybe @Leguark for this) know if / when you need review! 👍

**Comment by Leguark** [comment]
I think this is stuck. I am planning to come back to it directly with tensorflow and then decide if I port it to theano. Lets leave it open so I can use Andrew hints for it

**Comment by alexanderzimmerman** [comment]
@Leguark , will you maybe document what still needs to be done here on #276 and close this PR?

**Comment by alexanderzimmerman** [comment]
We had some offline conversation about how to handle PR's in this state. Since the plan is to use this branch only as a reference (e.g. for #276 ) and to implement the changes on a new branch (after #274 ) with a new PR, I am closing this PR.

This leaves the problem of how to not lose Andrew's work, since the commits are on his fork. So I fetched the PR's branch (which shows up with `ls-remote --refs origin` and made a branch for it in our repository: https://github.com/cgre-aachen/gempy/tree/reference/pr252

**Comment by AndrewAnnex** [comment]
@alexanderzimmerman the only thing worth keeping from this pr are the additions to the test area, this can be done easily by rebaseing this branch after #274/#276. If the added tests are needed for one/either or some later pr the changes including the git attributions could also be merged into whatever pr branch is being developed.

**Pull request closed without merging**
