### PR TITLE
Can GemPy plot any direction's 2D section,for example NW-SE？

### PR DESCRIPTION
**Pull request by wh19971014**
Relates to <issue>
I want to plot a 2D section of selected direction, it occured the error "the xy values of the first point must be smaller than second(fix soon)",but the endpoint's X Y values at both ends of the profile can't be changed.The error 2D section of NW-SE direction can't be plotted,I am in hurry to get that function,I upload my code internet.Can't the profile in this direction be drawn successfully?

****
http://localhost:8888/notebooks/ch1-7b-Topography.ipynb#

### CODE REVIEW

**Comment by Japhiolite** [comment]
Just to be sure: @wh19971014  you know that there is the function argument `show_topo=False` in the plotting function for sections? If you set `show_topo=False` any section orientation is possible.

**Comment by wh19971014** [comment]
> Just to be sure: @wh19971014 you know that there is the function argument `show_topo=False` in the plotting function for sections? If you set `show_topo=False` any section orientation is possible.

Hi, @Japhiolite .Yes,I know  that there is the function argument `show_topo=False` in the plotting function for sections,but I want to show the topography in 2D section at any direction

**Comment by Japhiolite** [comment]
With the currently released version, this is not possible.
However, refer to issue #390 where I suggested solutions.

**Comment by Leguark** [comment]
@Japhiolite is this issue solved by your pull request?

**Comment by Japhiolite** [comment]
Yes should be solved. I want to / need to write some tests for it though, to ensure that topography is cut correctly.

**Comment by AIjieling** [comment]
hi

**Comment by AIjieling** [comment]
can i ask a quension, i want to design GUI with gempy, by pyqt? py what ? have  example ,tiis is important

**Pull request closed without merging**
