### PR TITLE
Moving documentation from jupyter to sphinx

### PR DESCRIPTION
**Pull request by Leguark**
# Description
Pull request to deal with #273

Tasks:
- [X] created examples folder and add one example
- [ ] Find a way to convert the notebooks to a sphinx gallery syntaxis
- [X] Update sphinx config file to generate the html pages from the examples folder
- [ ] Check if readthedocs can render the html

!!
- [ ] Remember to set the default branch of read the docs back to the master once we merge the pull request

Relates to #273

# Checklist
- [ ] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [ ] My code uses type hinting for function and method arguments and return values.
- [ ] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines](http://google.github.io/styleguide/pyguide.html).
- [ ] I have created tests which entirely cover my code.
- [ ] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [ ] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by Leguark** [comment]
Read the docs is failing installing theano. Can we try to go back to the idea of github actions?

https://github.com/ammaraskar/sphinx-action

https://github.com/ammaraskar/sphinx-action-test

**Comment by Leguark** [comment]
### travis:
So travis seems to work fine. Now I stuck trying to deployed the built html to the gh-pages branch of gempy 

https://docs.travis-ci.com/user/deployment/pages/

### Converting jupyter to sphinx:

https://jupytext.readthedocs.io/en/latest/formats.html#sphinx-gallery-scripts

**Comment by Leguark** [comment]
running

https://cgre-aachen.github.io/gempy/examples/Horizontal.html#sphx-glr-examples-horizontal-py

**Comment by Leguark** [comment]
Using jupytext I was able to convert all notebooks in py files that can be rendered by gallery. However all they need a rst header with the title and check that it compiles. I think makes sense for me to finish this part.

Once that is done and the page is created in github pages via travis, we can merge this pull request so I can continue with refactoring but there are still a couple of things to be done @alexanderzimmerman:
 - sphinx test
- sphinx hyperlink https://sphinx-gallery.github.io/stable/configuration.html#add-intersphinx-links-to-your-examples

**Comment by alexanderzimmerman** [comment]
> Once that is done and the page is created in github pages via travis, we can merge this pull request so I can continue with refactoring but there are still a couple of things to be done @alexanderzimmerman:

If I understand correctly, then you intend to merge this PR on your own and, after that, I can continue the remaining work on #273.

> * sphinx test

I don't understand what you mean by "sphinx test" here. Per #273 , the point is that notebooks were being run as tests before, so the scripts that you replaced the notebooks with must now be run as tests instead. You shouldn't merge this PR to master if those tests aren't being run. So I must be misunderstanding something. What still needs to be done with the tests? I'll move forward with getting this branch running locally so I can observe the test behavior.

> * sphinx hyperlink https://sphinx-gallery.github.io/stable/configuration.html#add-intersphinx-links-to-your-examples

We didn't have hyperlinking in the notebooks before, right? It's just another feature we can (and probably should) add. It sounds like a small issue that doesn't need to slow down the task at hand.

**Comment by alexanderzimmerman** [comment]
Locally, 47 tests passed and 5 failed. Some tests are failing because of relative file paths like this in `test_utilities.py`

    input_path = os.path.dirname(__file__)+'/../../notebooks/data'

**Comment by alexanderzimmerman** [comment]
It look like [Travis is also having trouble with at least one relative file path](https://travis-ci.org/github/cgre-aachen/gempy/builds/676914916).

**Comment by alexanderzimmerman** [comment]
When I use the same procedure to run all tests locally on master, all 72 tests pass (and two are skipped, but no failures).

**Comment by alexanderzimmerman** [comment]
Master has `gempy/notebooks/data` and the sphinx-gallery branch does not.

**Comment by alexanderzimmerman** [comment]
Must be `gempy/examples/data` now.

**Comment by Leguark** [comment]
yes, I know I am working on all of that yet

**Comment by alexanderzimmerman** [comment]
> yes, I know I am working on all of that yet

Ah whoops. I just refactored that, didn't change anything else. So now only four tests fail.

**Pull request closed without merging**
