### PR TITLE
[WIP] Fix pd warning

### PR DESCRIPTION
**Pull request by AlexanderJuestel**
# Description
Please include a summary of the changes.

Relates to #682

### CODE REVIEW

**Review by Japhiolite — COMMENTED** [review]
Have you tested if this works? I think, if `inplace` is removed, the change has to be assigned to a variable.

**Comment by AlexanderJuestel** [comment]
Haven't tested it yet......

**Review by Japhiolite — CHANGES_REQUESTED** [review]
Tested the proposed changes, which yield expected errors. Removing the deprecated `inplace` argument must go hand in hand with assigning the change, i.e.
```python
self._surface_points.df['surface'] = self._surface_points.df['surface'].cat.add_categories(surface_list)
self._orientations.df['surface'] = self._orientations.df['surface'].cat.add_categories(surface_list)
```
should do the trick.

**Comment by AlexanderJuestel** [comment]
Thanks for testing! I will change the PR accordingly and try to fix the other obsolete inplace places as well

**Review by Japhiolite — APPROVED** [review]

**Comment by AlexanderJuestel** [comment]
fixes #682

**Pull request merged**
